"""metrodef3d package."""

__version__ = "0.1.0"

RECIPE_SCHEMA_VERSION = 1
METADATA_SCHEMA_VERSION = 1
VISIBLE_DEFECT_SCHEMA_VERSION = 1
PIXEL_SCALE_SCHEMA_VERSION = 1
DATASET_SUMMARY_SCHEMA_VERSION = 1
QUALITY_MANIFEST_SCHEMA_VERSION = 1
